name: EditArmorStands
main: de.themoep.EditArmorStands.EditArmorStands
version: '${minecraft.plugin.version}'
description: ${project.description}
commands:
   editarmorstand:      
      aliases: [editas, eas]
      description: Command to edit armor stands
      usage: |
             /<command>
              - Rightclick an ArmorStand in the next 10s to select it
             /<command> exit
              - Exit the editing mode
             /<command> info
              - Show some info about the armor stand
             /<command> copy
              - Copy ArmorStand data
             /<command> paste
              - Paste ArmorStand data
             /<command> items
              - Show a gui to manipulate the items/armor
             /<command> name <name>
              - Set the ArmorStand's name, use & for colorcodes
             /<command> move <x> <y> <z>
              - Move the ArmorStand, use ~ for relatives
             /<command> [namevisible|gravity|visible|base|arms|size]
              - Toggle the option
             /<command> <bodypart> [pitch|yaw|roll] <degree>
              - Set an angle, use ~ for relatives
             /<command> <bodypart> <pitch> <yaw> <roll>
              - Set all angles of a body part at once, use ~ for relatives
             Bodyparts: head, body, leftarm, rightarm, leftleg, rightleg.
             (r, y, p, h, ra, ll etc. are possible!)
      permissions: editarmorstands.command
permissions:
   editarmorstands.*:
      description: Gives access to all EditArmorStands features
      children:
         editarmorstands.command.*: true
         editarmorstands.nametag.*: true
         editarmorstands.openinventory: true
   editarmorstands.user:
      description: A collection of permissions a normal user should have.
      children:
         editarmorstands.command: true
         editarmorstands.command.info: true
         editarmorstands.command.copy: true
         editarmorstands.command.paste: true
         editarmorstands.command.paste.pose: true
         editarmorstands.command.paste.data: true
         editarmorstands.command.items: true
         editarmorstands.command.gravity: true
         editarmorstands.command.glowing: true
         editarmorstands.command.base: true
         editarmorstands.command.arms: true
         editarmorstands.command.size: true
         editarmorstands.command.pose: true
         editarmorstands.command.move: true
         editarmorstands.place.name: true
         editarmorstands.nametag.name: true
         editarmorstands.nametag.name.clear: true
         editarmorstands.openinventory: true
   editarmorstands.command.*:
      description: Gives access to all EditArmorStands commands
      children:
         editarmorstands.command: true
         editarmorstands.command.info: true
         editarmorstands.command.copy: true
         editarmorstands.command.paste: true
         editarmorstands.command.paste.pose: true
         editarmorstands.command.paste.settings: true
         editarmorstands.command.paste.name: true
         editarmorstands.command.paste.items: true
         editarmorstands.command.items: true
         editarmorstands.command.name: true
         editarmorstands.command.name.colored: true
         editarmorstands.command.namevisible: true
         editarmorstands.command.vulnerable: true
         editarmorstands.command.gravity: true
         editarmorstands.command.visible: true
         editarmorstands.command.glowing: true
         editarmorstands.command.invulnerable: true
         editarmorstands.command.marker: true
         editarmorstands.command.base: true
         editarmorstands.command.arms: true
         editarmorstands.command.size: true
         editarmorstands.command.pose: true
         editarmorstands.command.move: true
         editarmorstands.command.move.nextblock: true
         editarmorstands.command.move.unlimited: true
   editarmorstands.nametag.*:
      description: Gives access to all NameTag options
      children:
         editarmorstands.nametag.name: true
         editarmorstands.nametag.name.colored: true
         editarmorstands.nametag.name.clear: true
   editarmorstands.command.info:
      description: Allows a player to show a some info about an armostand
      default: op
   editarmorstands.command.copy:
      description: Allows a player to copy armorstand data
      default: op
   editarmorstands.command.paste:
      description: Allows a player to paste armorstand data
      default: op
   editarmorstands.command.paste.items:
      description: Allows a player to paste items onto an armorstand
      default: op
   editarmorstands.command.paste.pose:
      description: Allows a player to paste the pose onto an armorstand
      default: op
   editarmorstands.command.paste.name:
      description: Allows a player to paste the custom name onto an armorstand
      default: op
   editarmorstands.command.paste.settings:
      description: Allows a player to paste the settings onto an armorstand
      default: op
   editarmorstands.place.name:
      description: Allows a player to name an armor stand by placing a named item
      default: op
   editarmorstands.place.name.colored:
      description: Allows a player to name an armor stand by placing a named item
      default: op
   editarmorstands.command.name:
      description: Allows a player to set the name of an armorstand
      default: op
   editarmorstands.command.name.colored:
      description: Allows a player to set colored names
      default: op
   editarmorstands.command.namevisible:
      description: Allows a player to make custom names visible
      default: op
   editarmorstands.command.vulnerable:
      description: Allows a player to make an armorstand invulnerable/vulnerable
      default: op
   editarmorstands.command.gravity:
      description: Allows a player to turn gravity on/off on a an armorstand
      default: op
   editarmorstands.command.visible:
      description: Allows a player to make an armorstand visible/invisible
      default: op
   editarmorstands.command.glowing:
      description: Allows a player to make an armorstand glowing/non glowing
      default: op
   editarmorstands.command.invulnerable:
      description: Allows a player to make an armorstand invulnarable
      default: op
   editarmorstands.command.marker:
      description: Allows a player to make an armorstand a marker
      default: op
   editarmorstands.command.base:
      description: Allows a player to make an armorstands base visible/invisible
      default: op
   editarmorstands.command.arms:
      description: Makes it so a player can gie/remove arms from an armorstand
      default: op
   editarmorstands.command.size:
      description: Allows a player to change the size of an armorstand
      default: op
   editarmorstands.command.pose:
      description: Allows a player to pose the armorstand
      default: op
   editarmorstands.command.move:
      description: Allows a player to move an armorstand
      default: op
   editarmorstands.command.move.nextblock:
      description: Allows a player to move an armorstand onto the next block (only 1 block at the time)
      default: op
   editarmorstands.command.move.unlimited:
      description: Allows a player to move an armorstand unlimited blocks away
      default: op
   editarmorstands.nametag.name:
      description: Allows a player to name armorstands via rightclick with a nametag
      default: op
   editarmorstands.nametag.name.colored:
      description: Allows a player to use colored names via nametags
      default: op
   editarmorstands.nametag.name.clear:
      description: Allows a player to clear the name of an armorstand with an empty nametag
      default: op
   editarmorstands.openinventory:
      description: Allows a player to open the inventory via rightclicking on an armor stand
      default: op